- kosmorrolib/ephemerides.py
- test/__init__.py
- test/ephemerides.py
> fix: set times are now correct

- .coveragerc
- .github/workflows/pythonapp.yml
- .gitignore
- Pipfile
- Pipfile.lock
- README.md
> Add codecov

- kosmorrolib/core.py
- kosmorrolib/data.py
- kosmorrolib/dumper.py
- kosmorrolib/ephemerides.py
- test/dumper.py
- test/ephemerides.py
> Compute more accurate Moon phase

- kosmorro
- kosmorrolib/data.py
| Related issues | _none_
- Remove the `--altitude` command argument (useless, since not implemented yet)
- Enhance performance on the position Topo creation
> Enhance position

- kosmorrolib/data.py
- test/ephemerides.py
> fix(moonphase): fix the Moon phase prediction

- .pylintrc
- kosmorro
- kosmorrolib/data.py
- kosmorrolib/dumper.py
- kosmorrolib/events.py
- test/__init__.py
- test/dumper.py
- test/events.py
> Add support for opposition events

- kosmorro
- kosmorrolib/dumper.py
- kosmorrolib/ephemerides.py
- test/dumper.py
| Has BC-break   | yes
Don't compute the ephemerides if user did not give its position, since this has not real sense.
> feat(ephemerides): compute ephemerides if the position is set only

- kosmorrolib/core.py
- kosmorrolib/data.py
- kosmorrolib/dumper.py
- kosmorrolib/events.py
- test/__init__.py
- test/core.py
- test/dumper.py
- test/events.py
(WIP)
| Related issues | Fix #25 
> Add support for conjunctions

- .github/workflows/pythonapp.yml
- .github/workflows/release.yml
- .gitignore
- .scripts/build/getlangs.py
- CONTRIBUTING.md
- MANIFEST.in
- Pipfile
- Pipfile.lock
- kosmorrolib/core.py
- kosmorrolib/data.py
- kosmorrolib/dumper.py
- kosmorrolib/i18n.py
- kosmorrolib/locales/messages.pot
- kosmorrolib/main.py
- setup.cfg
- setup.py
- test/dumper.py
> Make the strings translatable

- Pipfile
- Pipfile.lock
- kosmorrolib/dumper.py
- kosmorrolib/locales/messages.pot
- kosmorrolib/main.py
- test/dumper.py
| Related issues | ø
Display colors in the text returned by the program.
A new argument, `--no-color`, can be used to disable them.
> Add colors in the text return

- .editorconfig
- .github/workflows/e2e.yml
- .scripts/tests-e2e.sh
- CONTRIBUTING.md
- MANIFEST.in
- kosmorrolib/main.py
> Add E2E tests

- kosmorrolib/assets/pdf/template.tex
- kosmorrolib/core.py
- kosmorrolib/data.py
- kosmorrolib/ephemerides.py
- kosmorrolib/events.py
- kosmorrolib/locales/messages.pot
- test/dumper.py
- test/events.py
| New feature?  | yes
| Related issues | Fix #49 
> Add support for maximal elongations of Mercury and Venus

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/e2e.yml
- .github/workflows/release.yml
- .gitignore
- .scripts/tests-e2e.sh
- README.md
- manpage/kosmorro.1.md
- setup.py
> Update doc, add man page

- .scripts/tests-e2e.sh
- kosmorrolib/ephemerides.py
- kosmorrolib/locales/messages.pot
- kosmorrolib/main.py
- manpage/kosmorro.1.md
- test/ephemerides.py
| Has BC-break   | yes: the --day, --month and --year arguments have been removed in the favor of a single one.
**Checklist:**
> feat: move the date to a single argument

- kosmorrolib/events.py
- test/events.py
| Related issues | Fix #48
**Checklist:**
> Prevent false detection of conjunctions

- kosmorrolib/data.py
- kosmorrolib/dumper.py
- kosmorrolib/events.py
- kosmorrolib/locales/messages.pot
- test/__init__.py
- test/data.py
- test/events.py
| Related issues | Fix #26 
**Checklist:**
> Add support for occultations

- kosmorrolib/dumper.py
- kosmorrolib/locales/messages.pot
| New feature? | no
**Checklist:**
> fix: Fix wording in the PDF output

- .github/workflows/commitlint.yml
- .github/workflows/e2e.yml
- .github/workflows/pythonapp.yml
> ci: run the tests in the PRs

- kosmorrolib/data.py
- kosmorrolib/dumper.py
- kosmorrolib/ephemerides.py
- kosmorrolib/locales/messages.pot
- kosmorrolib/main.py
- test/__init__.py
- test/dumper.py
- test/ephemerides.py
- test/testutils.py
| Related issues | Fix #52 
| Has BC-break   | yes
**Checklist:**
> refactor: simplify ephemerides, remove dead code

- .gitignore
- .scripts/tests-e2e.sh
- kosmorrolib/assets/pdf/kosmorro.sty
- kosmorrolib/assets/pdf/template.tex
- kosmorrolib/dumper.py
- kosmorrolib/locales/messages.pot
- kosmorrolib/main.py
- manpage/kosmorro.1.md
- test/dumper.py
> Display a graph in the PDF output for the ephemerides

- .github/workflows/i18n.yml
- .github/workflows/pylint.yml
- .github/workflows/unit-tests.yml
Split the Python workflow into three separate workflows to give the developer all the issues immediately.
> Split Python workflow to enhance DX

- kosmorrolib/assets/pdf/kosmorro.sty
- kosmorrolib/assets/pdf/template.tex
- kosmorrolib/dumper.py
- kosmorrolib/locales/messages.pot
**Checklist:**
Fix an issue introduces by #82, where the new graph is not translated.
> Add support for translation to the PDF graph

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/e2e.yml
- .github/workflows/release.yml
- .scripts/tests-e2e.sh
- Makefile
- manpage/README.md
- manpage/kosmorro.7.md
- setup.py
| Related issues | Fix #70 
**Checklist:**
> Add manpage to explain terms

- kosmorrolib/core.py
- kosmorrolib/dateutil.py
- kosmorrolib/dumper.py
- kosmorrolib/ephemerides.py
- kosmorrolib/events.py
- kosmorrolib/locales/messages.pot
- kosmorrolib/main.py
- test/__init__.py
- test/dateutil.py
- test/dumper.py
**Checklist:**
Fix the dates issue in the ephemerides
> Avoid returning ephemerides for yesterday or tomorrow

- .coveragerc
- .github/workflows/unit-tests.yml
- Pipfile
- Pipfile.lock
- README.md
> Replace Codecov by Coveralls

- .github/workflows/release.yml
- Makefile
> ci: release locales through a workflow

- .github/workflows/e2e.yml
- kosmorrolib/data.py
- kosmorrolib/events.py
- kosmorrolib/locales/messages.pot
- manpage/kosmorro.7.md
- test/events.py
| Related issues | Fix #72 
**Checklist:**
> Add support for moon apogee and perigee

- .coveragerc
- .editorconfig
- .github/workflows/commitlint.yml
- .github/workflows/e2e.yml
- .github/workflows/i18n.yml
- .github/workflows/pylint.yml
- .github/workflows/unit-tests.yml
- .pylintrc
- .scripts/tests-e2e.sh
- Makefile
- Pipfile
- Pipfile.lock
- README.md
- config-comlipy.yml
- kosmorrolib/core.py
- kosmorrolib/dumper.py
- kosmorrolib/ephemerides.py
- kosmorrolib/events.py
- kosmorrolib/exceptions.py
- kosmorrolib/locales/messages.pot
- kosmorrolib/main.py
> Test on more Python versions and on macOS

- .github/dependabot.yml
- Pipfile.lock
> chore: fix dependencies

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/release.yml
> ci: fix syntax in the release workflow

- _kosmorro/dumper.py
- _kosmorro/i18n/strings.py
- _kosmorro/locales/messages.pot
- _kosmorro/main.py
| Related issues | Relates to #162
**Checklist:**
> fix: fix some issues introduced in #162

- _kosmorro/dumper.py
- _kosmorro/exceptions.py
- _kosmorro/i18n/strings.py
- _kosmorro/locales/messages.pot
- _kosmorro/main.py
| Related issues | Replaces #165
**Checklist:**
> Fix strings

- .github/workflows/dockerfile.yml
- Dockerfile
- setup.cfg
> build: fix Docker image build

- _kosmorro/__version__.py
- _kosmorro/debug.py
- _kosmorro/dumper.py
- _kosmorro/locales/messages.pot
| Related issues | Fix #185 
**Checklist:**
> fix(pdf): fix the failure on PDF saving

- .scripts/tests-e2e.sh
- Pipfile
- Pipfile.lock
- _kosmorro/geolocation.py
- _kosmorro/locales/messages.pot
- _kosmorro/main.py
- manpage/kosmorro.1.md
- setup.py
| Related issues | Fix #159 
| Has BC-break   | yes
**Checklist:**
> feat: replace latitude and longitude with one argument alone: --position

- _kosmorro/dumper.py
- _kosmorro/i18n/strings.py
- _kosmorro/locales/messages.pot
> Fix issues with Kosmorrolib v1.0 compatibility

- .github/workflows/e2e.yml
- _kosmorro/i18n/strings.py
> fix(events): fix event details display for maximal elongation

- _kosmorro/dumper.py
> fix(colors): use colors adapted on both dark and light background

- _kosmorro/environment.py
- _kosmorro/locales/messages.pot
- _kosmorro/main.py
- manpage/kosmorro.1.md
update man pages
| Related issues | Fix #210 
**Checklist:**
- [x ] I have updated the manpages
> feat: add support for the `NO_COLOR` environment variable

- _kosmorro/locales/messages.pot
- _kosmorro/main.py
> feat: add support for `KOSMORRO_POSITION` environment variable

- _kosmorro/locales/messages.pot
- _kosmorro/main.py
- kosmorro
> fix: fix locale support that led to an exception when it's not system-widely enabled

- .github/workflows/appimage.yml
- .gitignore
- AppImageBuilder.yml
- Makefile
- _kosmorro/locales/messages.pot
Adding AppImage generation to facilitate the distribution on Linux.
Fix #88
> build: generate AppImage file

- _kosmorro/dumper.py
- _kosmorro/locales/messages.pot
> fix(events): ignore unsupported event types

- Dockerfile
- Makefile
- Pipfile
- Pipfile.lock
- _kosmorro/dumper.py
- _kosmorro/exceptions.py
- _kosmorro/locales/messages.pot
- _kosmorro/main.py
- setup.py
- tests/dates.py
- tests/general.py
- tests/position.py
- tests/timezone.py
- tests/utils.py
| Bug fix?       | yes/
**Checklist:**
> fix: use Babel to localize the dates

- kosmorro/__main__.py
- kosmorro/locales/messages.pot
- kosmorro/utils.py
- tests/dates.py
- tests/output.py
> feat: send error and warning messages in standard error instead of standard output

- .github/workflows/tests.yml
- poetry.lock
- pyproject.toml
BREAKING CHANGE: Python 3.7 is not supported anymore
> build: add support for Python 3.11

- .github/workflows/tests.yml
- poetry.lock
- pyproject.toml
> fix: compatibility with Python 3.12

- .all-contributorsrc
- CONTRIBUTORS.md
See https://github.com/Kosmorro/kosmorro/pull/381#issuecomment-2646510081
> chore(contributors): update தமிழ்நேரக்குழு's information

- kosmorro/i18n/strings.py
- kosmorro/locales/messages.pot
- tests/events.py
> feat: add support for seasons and lunar eclipses

- kosmorro/dumper.py
- kosmorro/locales/messages.pot
- tests/dates.py
- tests/position.py
- tests/timezone.py
- tests/utils.py
| Related issues | thanks twitch chat
> feat: remove label for moon phase
